# Tensors

- 1D Tensors: Vectors
    - Represented as [features]
    - Example: [3, 5, 7, 9]

- 2D Tensors: Matrices
    - Represented as [rows x columns]
    - Example: [[1, 2, 3],
                [4, 5, 6]]

- 3D Tensors: Stacked Matrices / Sequences
    - Represented as [depth x rows x columns]
    - Example: Multiple matrices stacked together
    - Used in NLP (word embeddings over sequences) or time-series batches

- 4D Tensors: Batches of RGB Images
    - Represented as [batch size x channels x height x width]
    - Example: [32 x 3 x 224 x 224]
    - Each image has 3 channels (R, G, B)

- 5D Tensors: Batches of 3D Volumes / Videos
    - Represented as [batch size x frames/depth x channels x height x width]
    - Example: [8 x 16 x 3 x 224 x 224]
    - Used in video processing or medical imaging (CT/MRI scans)

In [ ]:
# =========================
# 1D Tensor (Vector)
# =========================
import torch

x = torch.tensor([3.0, 5.0, 7.0, 9.0], requires_grad=True)

y = x * 2 + 1  # simple element-wise operation
z = y.sum()    # scalar output for backward

z.backward()

print("x:", x)
print("y:", y)
print("grad:", x.grad)

In [ ]:
# =========================
# 2D Tensor (Matrix)
# =========================
import torch

A = torch.tensor([[1.0, 2.0, 3.0],
                  [4.0, 5.0, 6.0]], requires_grad=True)

B = A.T  # transpose operation
C = B * 2
loss = C.sum()

loss.backward()

print("A:\n", A)
print("B:\n", B)
print("Grad:\n", A.grad)

In [ ]:
# =========================
# 3D Tensor (Stacked Matrices)
# =========================
import torch

x = torch.randn(2, 3, 4, requires_grad=True)  
# [depth x rows x columns]

y = x ** 2
z = y.mean()

z.backward()

print("Shape:", x.shape)
print("Grad shape:", x.grad.shape)

In [ ]:
# =========================
# 4D Tensor (Images Batch)
# =========================
import torch

x = torch.randn(4, 3, 64, 64, requires_grad=True)
# [batch x channels x height x width]

conv_weight = torch.randn(3, 3, 3, 3, requires_grad=True)

# simple convolution-like operation (no nn module used)
y = torch.nn.functional.conv2d(x, conv_weight, padding=1)

loss = y.mean()
loss.backward()

print("Input shape:", x.shape)
print("Output shape:", y.shape)
print("Grad shape:", x.grad.shape)

In [ ]:
# =========================
# 5D Tensor (Video / 3D Data Batch)
# =========================
import torch

x = torch.randn(2, 10, 3, 32, 32, requires_grad=True)
# [batch x frames x channels x height x width]

y = x.pow(2)
loss = y.sum()

loss.backward()

print("Shape:", x.shape)
print("Grad shape:", x.grad.shape)

In [1]:
import torch
print(torch.__version__)

2.12.0+cpu


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


# Creating Tensor

In [4]:
# using empty
a = torch.empty(2,3)
print(a)
print(type(a))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [6]:
# using zeros
b = torch.zeros(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
# using rand
c = torch.rand(2,3)
print(c)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


In [11]:
# use of seed
torch.manual_seed(100)
d = torch.rand(2,3)
print(d)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [12]:
# use tensor
e = torch.tensor([[1,2,3], [4,5,6]])
print(e)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [22]:
# use arange
print(f"Using arange: {torch.arange(0,10,2)}")

# use linspace (linearly spaced)
print(f"Using linspace: {torch.linspace(0,10,10)}")

# use eye (identity matrix -> diagnals are 1)
print(f"Using eye: {torch.eye(5)}")

# use full
print(f"Using full: {torch.full((3,3), 5)}")

# To copy the shape of the tensor, use empty_like
print(f"Using empty_like: {torch.empty_like(e)}")

# To copy the shape of the tensor, use zeros_like
print(f"Using zeros_like: {torch.zeros_like(e)}")

# To copy the shape of the tensor, use ones_like
print(f"Using ones_like: {torch.ones_like(e)}")

# To copy the shape of the tensor, use rand_like
print(f"Using rand_like: {torch.rand_like(e, dtype=torch.float32)}")

# To convert tensor into float, use to()
print(f"Using to(): {e.to(torch.float32)}")


Using arange: tensor([0, 2, 4, 6, 8])
Using linspace: tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full: tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
Using empty_like: tensor([[4579660422986072064, 4635705220378015972, 4661726013461248228],
        [4681742012764214613, 4692750812811507940,                   0]])
Using zeros_like: tensor([[0, 0, 0],
        [0, 0, 0]])
Using ones_like: tensor([[1, 1, 1],
        [1, 1, 1]])
Using rand_like: tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
Using to(): tensor([[1., 2., 3.],
        [4., 5., 6.]])
